spring.application.name=GetHostel

server.port=${PORT:8080}
# File upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ashokspm}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:bowler}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG

cloudinary.cloud-name=vjvbynvq
cloudinary.api-key=887889111141224
cloudinary.api-secret=0D5oFf7xhEyW8j8Y7HB2MomQx-k